// GENERATED FILE — do not edit by hand.
// Source: Gitea swagger spec v1.27.2 (scripts/spec/swagger.json)
// Regenerate with: npm run generate
/* eslint-disable */
export interface RegistryParam {
	/** Parameter name in the Gitea API */
	api: string;
	/** Parameter name in the n8n UI */
	param: string;
	in: 'path' | 'query' | 'body';
	required: boolean;
	/** True when the UI exposes this as a raw-JSON field that must be parsed */
	json: boolean;
}

export interface RegistryEntry {
	method: string;
	path: string;
	params: RegistryParam[];
}

export const GITEA_API_VERSION = "1.27.2";

export const REGISTRY: Record<string, RegistryEntry> = {
	"repository.create": {
		method: "POST",
		path: "/user/repos",
		params: [
			{
				api: "auto_init",
				param: "auto_init",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "default_branch",
				param: "default_branch",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "description",
				param: "description",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "gitignores",
				param: "gitignores",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "issue_labels",
				param: "issue_labels",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "license",
				param: "license",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "name",
				param: "name",
				in: "body",
				required: true,
				json: false,
			},
			{
				api: "object_format_name",
				param: "object_format_name",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "private",
				param: "private",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "readme",
				param: "readme",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "template",
				param: "template",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "trust_model",
				param: "trust_model",
				in: "body",
				required: false,
				json: false,
			},
		],
	},
	"repository.delete": {
		method: "DELETE",
		path: "/repos/{owner}/{repo}",
		params: [
			{
				api: "owner",
				param: "owner",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "repo",
				param: "repo",
				in: "path",
				required: true,
				json: false,
			},
		],
	},
	"repository.get": {
		method: "GET",
		path: "/repos/{owner}/{repo}",
		params: [
			{
				api: "owner",
				param: "owner",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "repo",
				param: "repo",
				in: "path",
				required: true,
				json: false,
			},
		],
	},
	"repository.listCommits": {
		method: "GET",
		path: "/repos/{owner}/{repo}/commits",
		params: [
			{
				api: "owner",
				param: "owner",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "repo",
				param: "repo",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "sha",
				param: "sha",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "path",
				param: "path",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "since",
				param: "since",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "until",
				param: "until",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "stat",
				param: "stat",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "verification",
				param: "verification",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "files",
				param: "files",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "page",
				param: "page",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "limit",
				param: "limit",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "not",
				param: "not",
				in: "query",
				required: false,
				json: false,
			},
		],
	},
	"repository.listTags": {
		method: "GET",
		path: "/repos/{owner}/{repo}/tags",
		params: [
			{
				api: "owner",
				param: "owner",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "repo",
				param: "repo",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "page",
				param: "page",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "limit",
				param: "limit",
				in: "query",
				required: false,
				json: false,
			},
		],
	},
	"repository.search": {
		method: "GET",
		path: "/repos/search",
		params: [
			{
				api: "q",
				param: "q",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "topic",
				param: "topic",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "includeDesc",
				param: "includeDesc",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "uid",
				param: "uid",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "priority_owner_id",
				param: "priority_owner_id",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "team_id",
				param: "team_id",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "starredBy",
				param: "starredBy",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "private",
				param: "private",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "is_private",
				param: "is_private",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "template",
				param: "template",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "archived",
				param: "archived",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "mode",
				param: "mode",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "exclusive",
				param: "exclusive",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "sort",
				param: "sort",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "order",
				param: "order",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "page",
				param: "page",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "limit",
				param: "limit",
				in: "query",
				required: false,
				json: false,
			},
		],
	},
	"branch.create": {
		method: "POST",
		path: "/repos/{owner}/{repo}/branches",
		params: [
			{
				api: "owner",
				param: "owner",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "repo",
				param: "repo",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "new_branch_name",
				param: "new_branch_name",
				in: "body",
				required: true,
				json: false,
			},
			{
				api: "old_branch_name",
				param: "old_branch_name",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "old_ref_name",
				param: "old_ref_name",
				in: "body",
				required: false,
				json: false,
			},
		],
	},
	"branch.get": {
		method: "GET",
		path: "/repos/{owner}/{repo}/branches/{branch}",
		params: [
			{
				api: "owner",
				param: "owner",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "repo",
				param: "repo",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "branch",
				param: "branch",
				in: "path",
				required: true,
				json: false,
			},
		],
	},
	"branch.list": {
		method: "GET",
		path: "/repos/{owner}/{repo}/branches",
		params: [
			{
				api: "owner",
				param: "owner",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "repo",
				param: "repo",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "page",
				param: "page",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "limit",
				param: "limit",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "q",
				param: "q",
				in: "query",
				required: false,
				json: false,
			},
		],
	},
	"file.create": {
		method: "POST",
		path: "/repos/{owner}/{repo}/contents/{filepath}",
		params: [
			{
				api: "owner",
				param: "owner",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "repo",
				param: "repo",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "filepath",
				param: "filepath",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "author",
				param: "author",
				in: "body",
				required: false,
				json: true,
			},
			{
				api: "branch",
				param: "branch",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "committer",
				param: "committer",
				in: "body",
				required: false,
				json: true,
			},
			{
				api: "content",
				param: "content",
				in: "body",
				required: true,
				json: false,
			},
			{
				api: "dates",
				param: "dates",
				in: "body",
				required: false,
				json: true,
			},
			{
				api: "force_push",
				param: "force_push",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "message",
				param: "message",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "new_branch",
				param: "new_branch",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "signoff",
				param: "signoff",
				in: "body",
				required: false,
				json: false,
			},
		],
	},
	"file.delete": {
		method: "DELETE",
		path: "/repos/{owner}/{repo}/contents/{filepath}",
		params: [
			{
				api: "owner",
				param: "owner",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "repo",
				param: "repo",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "filepath",
				param: "filepath",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "author",
				param: "author",
				in: "body",
				required: false,
				json: true,
			},
			{
				api: "branch",
				param: "branch",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "committer",
				param: "committer",
				in: "body",
				required: false,
				json: true,
			},
			{
				api: "dates",
				param: "dates",
				in: "body",
				required: false,
				json: true,
			},
			{
				api: "force_push",
				param: "force_push",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "message",
				param: "message",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "new_branch",
				param: "new_branch",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "sha",
				param: "sha",
				in: "body",
				required: true,
				json: false,
			},
			{
				api: "signoff",
				param: "signoff",
				in: "body",
				required: false,
				json: false,
			},
		],
	},
	"file.get": {
		method: "GET",
		path: "/repos/{owner}/{repo}/contents/{filepath}",
		params: [
			{
				api: "owner",
				param: "owner",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "repo",
				param: "repo",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "filepath",
				param: "filepath",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "ref",
				param: "ref",
				in: "query",
				required: false,
				json: false,
			},
		],
	},
	"file.update": {
		method: "PUT",
		path: "/repos/{owner}/{repo}/contents/{filepath}",
		params: [
			{
				api: "owner",
				param: "owner",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "repo",
				param: "repo",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "filepath",
				param: "filepath",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "author",
				param: "author",
				in: "body",
				required: false,
				json: true,
			},
			{
				api: "branch",
				param: "branch",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "committer",
				param: "committer",
				in: "body",
				required: false,
				json: true,
			},
			{
				api: "content",
				param: "content",
				in: "body",
				required: true,
				json: false,
			},
			{
				api: "dates",
				param: "dates",
				in: "body",
				required: false,
				json: true,
			},
			{
				api: "force_push",
				param: "force_push",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "from_path",
				param: "from_path",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "message",
				param: "message",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "new_branch",
				param: "new_branch",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "sha",
				param: "sha",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "signoff",
				param: "signoff",
				in: "body",
				required: false,
				json: false,
			},
		],
	},
	"issue.addLabels": {
		method: "POST",
		path: "/repos/{owner}/{repo}/issues/{index}/labels",
		params: [
			{
				api: "owner",
				param: "owner",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "repo",
				param: "repo",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "index",
				param: "index",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "labels",
				param: "labels",
				in: "body",
				required: false,
				json: true,
			},
		],
	},
	"issue.create": {
		method: "POST",
		path: "/repos/{owner}/{repo}/issues",
		params: [
			{
				api: "owner",
				param: "owner",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "repo",
				param: "repo",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "assignee",
				param: "assignee",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "assignees",
				param: "assignees",
				in: "body",
				required: false,
				json: true,
			},
			{
				api: "body",
				param: "body",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "closed",
				param: "closed",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "due_date",
				param: "due_date",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "labels",
				param: "labels",
				in: "body",
				required: false,
				json: true,
			},
			{
				api: "milestone",
				param: "milestone",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "projects",
				param: "projects",
				in: "body",
				required: false,
				json: true,
			},
			{
				api: "ref",
				param: "ref",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "title",
				param: "title",
				in: "body",
				required: true,
				json: false,
			},
		],
	},
	"issue.createComment": {
		method: "POST",
		path: "/repos/{owner}/{repo}/issues/{index}/comments",
		params: [
			{
				api: "owner",
				param: "owner",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "repo",
				param: "repo",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "index",
				param: "index",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "body",
				param: "body",
				in: "body",
				required: true,
				json: false,
			},
		],
	},
	"issue.get": {
		method: "GET",
		path: "/repos/{owner}/{repo}/issues/{index}",
		params: [
			{
				api: "owner",
				param: "owner",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "repo",
				param: "repo",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "index",
				param: "index",
				in: "path",
				required: true,
				json: false,
			},
		],
	},
	"issue.list": {
		method: "GET",
		path: "/repos/{owner}/{repo}/issues",
		params: [
			{
				api: "owner",
				param: "owner",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "repo",
				param: "repo",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "state",
				param: "state",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "labels",
				param: "labels",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "q",
				param: "q",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "type",
				param: "type",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "milestones",
				param: "milestones",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "since",
				param: "since",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "before",
				param: "before",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "created_by",
				param: "created_by",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "assigned_by",
				param: "assigned_by",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "mentioned_by",
				param: "mentioned_by",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "page",
				param: "page",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "limit",
				param: "limit",
				in: "query",
				required: false,
				json: false,
			},
		],
	},
	"issue.listComments": {
		method: "GET",
		path: "/repos/{owner}/{repo}/issues/{index}/comments",
		params: [
			{
				api: "owner",
				param: "owner",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "repo",
				param: "repo",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "index",
				param: "index",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "since",
				param: "since",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "before",
				param: "before",
				in: "query",
				required: false,
				json: false,
			},
		],
	},
	"issue.listLabels": {
		method: "GET",
		path: "/repos/{owner}/{repo}/labels",
		params: [
			{
				api: "owner",
				param: "owner",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "repo",
				param: "repo",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "page",
				param: "page",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "limit",
				param: "limit",
				in: "query",
				required: false,
				json: false,
			},
		],
	},
	"issue.search": {
		method: "GET",
		path: "/repos/issues/search",
		params: [
			{
				api: "state",
				param: "state",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "labels",
				param: "labels",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "milestones",
				param: "milestones",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "q",
				param: "q",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "type",
				param: "type",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "since",
				param: "since",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "before",
				param: "before",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "assigned",
				param: "assigned",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "created",
				param: "created",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "mentioned",
				param: "mentioned",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "review_requested",
				param: "review_requested",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "reviewed",
				param: "reviewed",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "owner",
				param: "owner",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "created_by",
				param: "created_by",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "team",
				param: "team",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "page",
				param: "page",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "limit",
				param: "limit",
				in: "query",
				required: false,
				json: false,
			},
		],
	},
	"issue.update": {
		method: "PATCH",
		path: "/repos/{owner}/{repo}/issues/{index}",
		params: [
			{
				api: "owner",
				param: "owner",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "repo",
				param: "repo",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "index",
				param: "index",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "assignee",
				param: "assignee",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "assignees",
				param: "assignees",
				in: "body",
				required: false,
				json: true,
			},
			{
				api: "body",
				param: "body",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "content_version",
				param: "content_version",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "due_date",
				param: "due_date",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "milestone",
				param: "milestone",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "projects",
				param: "projects",
				in: "body",
				required: false,
				json: true,
			},
			{
				api: "ref",
				param: "ref",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "state",
				param: "state",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "title",
				param: "title",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "unset_due_date",
				param: "unset_due_date",
				in: "body",
				required: false,
				json: false,
			},
		],
	},
	"pullRequest.create": {
		method: "POST",
		path: "/repos/{owner}/{repo}/pulls",
		params: [
			{
				api: "owner",
				param: "owner",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "repo",
				param: "repo",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "allow_maintainer_edit",
				param: "allow_maintainer_edit",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "assignee",
				param: "assignee",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "assignees",
				param: "assignees",
				in: "body",
				required: false,
				json: true,
			},
			{
				api: "base",
				param: "base",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "body",
				param: "body",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "due_date",
				param: "due_date",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "head",
				param: "head",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "labels",
				param: "labels",
				in: "body",
				required: false,
				json: true,
			},
			{
				api: "milestone",
				param: "milestone",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "reviewers",
				param: "reviewers",
				in: "body",
				required: false,
				json: true,
			},
			{
				api: "team_reviewers",
				param: "team_reviewers",
				in: "body",
				required: false,
				json: true,
			},
			{
				api: "title",
				param: "title",
				in: "body",
				required: false,
				json: false,
			},
		],
	},
	"pullRequest.get": {
		method: "GET",
		path: "/repos/{owner}/{repo}/pulls/{index}",
		params: [
			{
				api: "owner",
				param: "owner",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "repo",
				param: "repo",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "index",
				param: "index",
				in: "path",
				required: true,
				json: false,
			},
		],
	},
	"pullRequest.list": {
		method: "GET",
		path: "/repos/{owner}/{repo}/pulls",
		params: [
			{
				api: "owner",
				param: "owner",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "repo",
				param: "repo",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "base_branch",
				param: "base_branch",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "state",
				param: "state",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "sort",
				param: "sort",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "milestone",
				param: "milestone",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "labels",
				param: "labels",
				in: "query",
				required: false,
				json: true,
			},
			{
				api: "poster",
				param: "poster",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "page",
				param: "page",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "limit",
				param: "limit",
				in: "query",
				required: false,
				json: false,
			},
		],
	},
	"pullRequest.merge": {
		method: "POST",
		path: "/repos/{owner}/{repo}/pulls/{index}/merge",
		params: [
			{
				api: "owner",
				param: "owner",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "repo",
				param: "repo",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "index",
				param: "index",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "delete_branch_after_merge",
				param: "delete_branch_after_merge",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "do",
				param: "do",
				in: "body",
				required: true,
				json: false,
			},
			{
				api: "force_merge",
				param: "force_merge",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "head_commit_id",
				param: "head_commit_id",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "merge_commit_id",
				param: "merge_commit_id",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "merge_message_field",
				param: "merge_message_field",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "merge_title_field",
				param: "merge_title_field",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "merge_when_checks_succeed",
				param: "merge_when_checks_succeed",
				in: "body",
				required: false,
				json: false,
			},
		],
	},
	"pullRequest.update": {
		method: "PATCH",
		path: "/repos/{owner}/{repo}/pulls/{index}",
		params: [
			{
				api: "owner",
				param: "owner",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "repo",
				param: "repo",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "index",
				param: "index",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "allow_maintainer_edit",
				param: "allow_maintainer_edit",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "assignee",
				param: "assignee",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "assignees",
				param: "assignees",
				in: "body",
				required: false,
				json: true,
			},
			{
				api: "base",
				param: "base",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "body",
				param: "body",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "content_version",
				param: "content_version",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "due_date",
				param: "due_date",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "labels",
				param: "labels",
				in: "body",
				required: false,
				json: true,
			},
			{
				api: "milestone",
				param: "milestone",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "state",
				param: "state",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "title",
				param: "title",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "unset_due_date",
				param: "unset_due_date",
				in: "body",
				required: false,
				json: false,
			},
		],
	},
	"release.create": {
		method: "POST",
		path: "/repos/{owner}/{repo}/releases",
		params: [
			{
				api: "owner",
				param: "owner",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "repo",
				param: "repo",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "body",
				param: "body",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "draft",
				param: "draft",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "name",
				param: "name",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "prerelease",
				param: "prerelease",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "tag_message",
				param: "tag_message",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "tag_name",
				param: "tag_name",
				in: "body",
				required: true,
				json: false,
			},
			{
				api: "target_commitish",
				param: "target_commitish",
				in: "body",
				required: false,
				json: false,
			},
		],
	},
	"release.delete": {
		method: "DELETE",
		path: "/repos/{owner}/{repo}/releases/{id}",
		params: [
			{
				api: "owner",
				param: "owner",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "repo",
				param: "repo",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "id",
				param: "id",
				in: "path",
				required: true,
				json: false,
			},
		],
	},
	"release.get": {
		method: "GET",
		path: "/repos/{owner}/{repo}/releases/{id}",
		params: [
			{
				api: "owner",
				param: "owner",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "repo",
				param: "repo",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "id",
				param: "id",
				in: "path",
				required: true,
				json: false,
			},
		],
	},
	"release.getLatest": {
		method: "GET",
		path: "/repos/{owner}/{repo}/releases/latest",
		params: [
			{
				api: "owner",
				param: "owner",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "repo",
				param: "repo",
				in: "path",
				required: true,
				json: false,
			},
		],
	},
	"release.list": {
		method: "GET",
		path: "/repos/{owner}/{repo}/releases",
		params: [
			{
				api: "owner",
				param: "owner",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "repo",
				param: "repo",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "draft",
				param: "draft",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "pre-release",
				param: "pre-release",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "page",
				param: "page",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "limit",
				param: "limit",
				in: "query",
				required: false,
				json: false,
			},
		],
	},
	"release.update": {
		method: "PATCH",
		path: "/repos/{owner}/{repo}/releases/{id}",
		params: [
			{
				api: "owner",
				param: "owner",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "repo",
				param: "repo",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "id",
				param: "id",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "body",
				param: "body",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "draft",
				param: "draft",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "name",
				param: "name",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "prerelease",
				param: "prerelease",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "tag_name",
				param: "tag_name",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "target_commitish",
				param: "target_commitish",
				in: "body",
				required: false,
				json: false,
			},
		],
	},
	"webhook.create": {
		method: "POST",
		path: "/repos/{owner}/{repo}/hooks",
		params: [
			{
				api: "owner",
				param: "owner",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "repo",
				param: "repo",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "active",
				param: "active",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "authorization_header",
				param: "authorization_header",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "branch_filter",
				param: "branch_filter",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "config",
				param: "config",
				in: "body",
				required: true,
				json: true,
			},
			{
				api: "events",
				param: "events",
				in: "body",
				required: false,
				json: true,
			},
			{
				api: "name",
				param: "name",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "type",
				param: "type",
				in: "body",
				required: true,
				json: false,
			},
		],
	},
	"webhook.delete": {
		method: "DELETE",
		path: "/repos/{owner}/{repo}/hooks/{id}",
		params: [
			{
				api: "owner",
				param: "owner",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "repo",
				param: "repo",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "id",
				param: "id",
				in: "path",
				required: true,
				json: false,
			},
		],
	},
	"webhook.list": {
		method: "GET",
		path: "/repos/{owner}/{repo}/hooks",
		params: [
			{
				api: "owner",
				param: "owner",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "repo",
				param: "repo",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "page",
				param: "page",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "limit",
				param: "limit",
				in: "query",
				required: false,
				json: false,
			},
		],
	},
	"user.get": {
		method: "GET",
		path: "/users/{username}",
		params: [
			{
				api: "username",
				param: "username",
				in: "path",
				required: true,
				json: false,
			},
		],
	},
	"user.getCurrent": {
		method: "GET",
		path: "/user",
		params: [],
	},
	"user.listOwnRepos": {
		method: "GET",
		path: "/user/repos",
		params: [
			{
				api: "page",
				param: "page",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "limit",
				param: "limit",
				in: "query",
				required: false,
				json: false,
			},
		],
	},
	"user.listRepos": {
		method: "GET",
		path: "/users/{username}/repos",
		params: [
			{
				api: "username",
				param: "username",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "page",
				param: "page",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "limit",
				param: "limit",
				in: "query",
				required: false,
				json: false,
			},
		],
	},
	"user.search": {
		method: "GET",
		path: "/users/search",
		params: [
			{
				api: "q",
				param: "q",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "uid",
				param: "uid",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "page",
				param: "page",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "limit",
				param: "limit",
				in: "query",
				required: false,
				json: false,
			},
		],
	},
	"organization.createRepo": {
		method: "POST",
		path: "/orgs/{org}/repos",
		params: [
			{
				api: "org",
				param: "org",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "auto_init",
				param: "auto_init",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "default_branch",
				param: "default_branch",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "description",
				param: "description",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "gitignores",
				param: "gitignores",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "issue_labels",
				param: "issue_labels",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "license",
				param: "license",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "name",
				param: "name",
				in: "body",
				required: true,
				json: false,
			},
			{
				api: "object_format_name",
				param: "object_format_name",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "private",
				param: "private",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "readme",
				param: "readme",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "template",
				param: "template",
				in: "body",
				required: false,
				json: false,
			},
			{
				api: "trust_model",
				param: "trust_model",
				in: "body",
				required: false,
				json: false,
			},
		],
	},
	"organization.get": {
		method: "GET",
		path: "/orgs/{org}",
		params: [
			{
				api: "org",
				param: "org",
				in: "path",
				required: true,
				json: false,
			},
		],
	},
	"organization.list": {
		method: "GET",
		path: "/orgs",
		params: [
			{
				api: "page",
				param: "page",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "limit",
				param: "limit",
				in: "query",
				required: false,
				json: false,
			},
		],
	},
	"organization.listMembers": {
		method: "GET",
		path: "/orgs/{org}/members",
		params: [
			{
				api: "org",
				param: "org",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "page",
				param: "page",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "limit",
				param: "limit",
				in: "query",
				required: false,
				json: false,
			},
		],
	},
	"organization.listRepos": {
		method: "GET",
		path: "/orgs/{org}/repos",
		params: [
			{
				api: "org",
				param: "org",
				in: "path",
				required: true,
				json: false,
			},
			{
				api: "page",
				param: "page",
				in: "query",
				required: false,
				json: false,
			},
			{
				api: "limit",
				param: "limit",
				in: "query",
				required: false,
				json: false,
			},
		],
	},
	"instance.getVersion": {
		method: "GET",
		path: "/version",
		params: [],
	},
};
